camera0: 4
camera1: 6
frame_width: 640
frame_height: 480
mono_calibration_frames: 89
stereo_calibration_frames: 89
view_resize: 1
checkerboard_box_size_scale : 0.08
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 100
