camera0: 4
camera1: 6
frame_width: 1280
frame_height: 960
mono_calibration_frames: 89
stereo_calibration_frames: 89
view_resize: 1
checkerboard_box_size_scale : 8.0
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 100
